# ml/report_generator.py

"""
Generate a PDF report for model comparison results.

Inputs:
- results: dict[str, dict]   # metrics per model
- roc_fig: matplotlib.figure.Figure or None
- dataset_summary: dict[str, any]
- llm_text: str              # LLM explanation text
- output_path: str           # where to save the PDF

Returns:
- output_path (for convenience)
"""

from pathlib import Path
from typing import Dict, Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)
from reportlab.lib import colors

import tempfile


def _dict_to_table_data(results: Dict[str, Dict[str, Any]]):
    # Collect all metric names
    metric_names = sorted({m for model in results.values() for m in model.keys() if m != "Confusion Matrix"})
    header = ["Model"] + metric_names
    rows = [header]

    for model_name, metrics in results.items():
        row = [model_name]
        for m in metric_names:
            val = metrics.get(m, "")
            if isinstance(val, float):
                row.append(f"{val:.4f}")
            else:
                row.append(str(val))
        rows.append(row)

    return rows


def _dataset_summary_to_paragraphs(styles, dataset_summary: Dict[str, Any]):
    parts = []
    if not dataset_summary:
        return parts

    parts.append(Paragraph("<b>Dataset Summary</b>", styles["Heading3"]))
    parts.append(Spacer(1, 0.2 * cm))

    for key, value in dataset_summary.items():
        parts.append(Paragraph(f"<b>{key}:</b> {value}", styles["Normal"]))
        parts.append(Spacer(1, 0.1 * cm))

    parts.append(Spacer(1, 0.3 * cm))
    return parts


def generate_model_comparison_pdf(
    results: Dict[str, Dict[str, Any]],
    roc_fig,
    dataset_summary: Dict[str, Any],
    llm_text: str,
    output_path: str,
) -> str:
    """
    Build a multi-page PDF report summarizing model comparison results.
    """
    output_path = str(output_path)
    pdf_file = Path(output_path)
    pdf_file.parent.mkdir(parents=True, exist_ok=True)

    # Setup document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    elements = []

    # ===== Title Page =====
    elements.append(Paragraph("Fraud Detection Model Comparison Report", styles["Title"]))
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph("Generated by Fraud Analytics Workbench", styles["Italic"]))
    elements.append(Spacer(1, 1 * cm))

    # Dataset summary
    elements.extend(_dataset_summary_to_paragraphs(styles, dataset_summary))

    # ===== Model Metrics Table =====
    elements.append(Paragraph("<b>Model Metrics Overview</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * cm))

    table_data = _dict_to_table_data(results)
    table = Table(table_data, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 0.5 * cm))

    # ===== ROC Curve (if provided) =====
    if roc_fig is not None:
        elements.append(Paragraph("<b>ROC Curves (Supervised Models)</b>", styles["Heading2"]))
        elements.append(Spacer(1, 0.2 * cm))

        # Save figure to temp PNG and embed
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            roc_fig.savefig(tmp.name, bbox_inches="tight", dpi=200)
            img_path = tmp.name

        img = Image(img_path, width=14 * cm, height=8 * cm)
        elements.append(img)
        elements.append(Spacer(1, 0.5 * cm))

    # ===== LLM Explanation =====
    if llm_text:
        elements.append(Paragraph("<b>LLM Interpretation</b>", styles["Heading2"]))
        elements.append(Spacer(1, 0.2 * cm))

        # Split LLM text into paragraphs for nicer formatting
        for paragraph in llm_text.split("\n\n"):
            clean_p = paragraph.strip()
            if not clean_p:
                continue
            elements.append(Paragraph(clean_p.replace("\n", "<br/>"), styles["Normal"]))
            elements.append(Spacer(1, 0.2 * cm))

    # Build PDF
    doc.build(elements)

    return output_path
